version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq_container
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672" # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  
  user-service:
    image: user-service
    container_name: user-service
    build:
      context: Users
      dockerfile: Application/Dockerfile
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    depends_on:
      - postgres
      - rabbitmq

#  user-worker:
#    image: user-worker
#    container_name: user-worker
#    build:
#      context: Users
#      dockerfile: Worker/Dockerfile
#    restart: unless-stopped
#    environment:
#      ASPNETCORE_ENVIRONMENT: "Development"
#    depends_on:
#      - postgres
#      - rabbitmq

volumes:
  postgres_data:
  rabbitmq_data:
